more tracing for error
2014-12-04 17:08:30.088 Go Swim[32554:13688659] *** Terminating app due to uncaught exception 'NoMethodError', reason: 'table_utils.rb:7:in `index_path_to_section_index:': undefined method `section' for 0:Fixnum (NoMethodError)
	from table_data.rb:26:in `cell:'
	from table.rb:105:in `block in delete_row:'
	from ns_index_path.rb:17:in `each'
	from table.rb:103:in `delete_row:'
	from app_delegate.rb:6:in `delete_row:'
	from table.rb:191:in `tableView:commitEditingStyle:forRowAtIndexPath:'