tracing Issue with index_path
erminating app due to uncaught exception 'NoMethodError', reason: 'table_utils.rb:6:in `index_path_to_section_index:': undefined method `section' for 0:Fixnum (NoMethodError)